receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  # Export tout vers LGTM via OTLP
  otlp:
    endpoint: http://lgtm:4317
    tls:
      insecure: true

  # Debug pour voir ce qui passe
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
