version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    entrypoint: [ "/bin/bash", "-c" ]
    command: >
      "/opt/keycloak/bin/kc.sh build --health-enabled=true &&
       /opt/keycloak/bin/kc.sh start-dev --health-enabled=true"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data_dev:/opt/keycloak/data
    networks:
      - dev-net

  # LGTM - All-in-one observability stack for development
  lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000"   # Grafana UI
      - "9090:9090"   # Prometheus/Mimir
      - "3100:3100"   # Loki
      - "3200:3200"   # Tempo
      - "4317:4317"   # OTLP gRPC (direct to LGTM)
      - "4318:4318"   # OTLP HTTP (direct to LGTM)
    environment:
      ENABLE_LOGS_ALL: "true"
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - lgtm_data_dev:/var/lib/grafana
      - ./backends/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - dev-net

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_DB: fastapi_proxy
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - "5431:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi -d fastapi_proxy"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-net

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    networks:
      - dev-net

volumes:
  keycloak_data_dev:
  lgtm_data_dev:
  postgres_data_dev:
  pgadmin_data_dev:

networks:
  dev-net:
    driver: bridge
