"""Domain models for OpenAI Embeddings API."""
from typing import Dict, Any, Optional, List, Union, Literal
from pydantic import BaseModel, Field, field_validator
from openai.types.create_embedding_response import Usage

class EmbeddingCreatePayload(BaseModel):
    """Payload for POST /v1/embeddings (mirrors openai.embeddings.create parameters).

    This model is designed to be compatible with the OpenAI SDK embeddings API
    while supporting additional proxy-specific functionality.
    """
    # Required parameters
    input: Union[str, List[str], List[int], List[List[int]]] = Field(
        ...,
        description="Input text to embed, encoded as a string or array of tokens"
    )
    model: str = Field(..., description="ID of the model to use")

    # Optional parameters
    dimensions: Optional[int] = Field(
        None,
        gt=0,
        description="The number of dimensions the resulting output embeddings should have"
    )
    encoding_format: Optional[Literal["float", "base64"]] = Field(
        "float",
        description="The format to return the embeddings in"
    )
    user: Optional[str] = Field(
        None,
        description="A unique identifier representing your end-user"
    )


    @field_validator("input", mode="before")
    @classmethod
    def validate_input_payload(cls, v):
        """Validate input parameter with OpenAI constraints."""
        if isinstance(v, str):
            if not v.strip():
                raise ValueError("Input cannot be an empty string")
        elif isinstance(v, list):
            if not v:
                raise ValueError("Input list cannot be empty")

            # Check token limits for arrays
            if v and isinstance(v[0], list):
                # Array of token arrays
                for i, token_array in enumerate(v):
                    if len(token_array) > 2048:
                        raise ValueError(f"Token array at index {i} cannot exceed 2048 dimensions")
        return v

    def to_openai_kwargs(self) -> Dict[str, Any]:
        """Return dict filtered to parameters accepted by openai.embeddings.create.

        Excludes proxy-only fields (extra_headers, extra_query, extra_body, timeout).
        """
        allowed = {
            "input": self.input,
            "model": self.model,
            "dimensions": self.dimensions,
            "encoding_format": self.encoding_format,
            "user": self.user,
        }
        return {k: v for k, v in allowed.items() if v is not None}

class Embedding(BaseModel):
    embedding: Union[str, List[float]]
    """The embedding vector, which is a list of floats.

    The length of vector depends on the model as listed in the
    [embedding guide](https://platform.openai.com/docs/guides/embeddings).
    """

    index: int
    """The index of the embedding in the list of embeddings."""

    object: Literal["embedding"]
    """The object type, which is always "embedding"."""

class CreateEmbeddingResponse(BaseModel):
    data: List[Embedding]
    """The list of embeddings generated by the model."""

    model: str
    """The name of the model used to generate the embedding."""

    object: Literal["list"]
    """The object type, which is always "list"."""

    usage: Usage
    """The usage information for the request."""
